version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image:  redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./analytics-api
    container_name: api
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      mongo:
        condition: service_healthy 
      redis:
        condition: service_healthy 

  kproducer:
    build: ./producer
    container_name: producer
    ports:
      - "8001:8001"
    environment:
      MONGO_URI: mongodb://mongo:27017
    depends_on:
      mongo:
        condition: service_healthy 
      redis:
        condition: service_healthy 
    volumes:
      - "./data:app/data"

  consumer:
    build: ./consumer
    container_name: consumer
    ports:
      - "8002:8002"
    environment:
      MONGO_URI: mongodb://mongo:27017
    depends_on:
      mongo:
        condition: service_healthy 
      redis:
        condition: service_healthy 
     
        
volumes:
  mongo-data:
  redis-data: